##version: "3.12.3"
##
##services:
##  startup_gift:
##    restart: always
##    build: .
##    container_name: startup
##    links:
##      - postgres:postgres
##      - redis:redis
##    volumes:
##      - startup_gift-django:/usr/src/app
##      - startup_gift-static:/usr/src/app/static
##    env_file:
##      - .env
##    ports:
##      - '8000:8000'
##    environment:
##      Debug: 'true'
##    command:
##      - bash -c 'python3 manage.py runserver 0.0.0.0:8000'
##
##  pg:
##    restart: always
##    image: postgres:latest
##    container_name: postgres_startup
##    ports:
##      - "5433:5432"
##    volumes:
##      - pgdata:/var/lib/posrgresql/data/
##
##volumes:
##  startup_gift-django:
##  startup_gift-static:
##  pgdata:
#
#
#
#version: '3.12'
#
#services:
#  postgres_service:
#    restart: always
#    image: postgres:alpine
#    container_name: postgres_container
#    environment:
#      - POSTGRES_PASSWORD=1
#    ports:
#      - 5434:5432
#    volumes:
#      - pgdata:/var/lib/postgresql/data/
#
#  web:
#    restart: always
#    build: .
#    container_name: serializer-full
#    #    links:
#    #      - postgres:postgres
#    #      - redis:redis
#    volumes:
#      - web-django:/usr/src/app
#      - web-static:/usr/src/app/static
#    env_file: .env
#    ports:
#      - "8000:8000"
#    depends_on:
#      - postgres_service
#
#    environment:
#      DEBUG: 'true'
#    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
#
##  nginx:
##    restart: always
##    build: ./nginx/
##    ports:
##      - "80:80"
##    volumes:
##      - web-static:/www/static
##    links:
##      - web:web
#
#
#
##  redis:
##    restart: always
##    image: redis:latest
##    ports:
##      - "6379:6379"
##    volumes:
##      - redisdata:/data
#
#volumes:
#  web-django:
#  web-static:
#  pgdata:
##  redisdata:



services:
  postgres_service:
    restart: always
    image: postgres:alpine
    container_name: startup_container
    environment:
      - POSTGRES_PASSWORD=1
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/

  web:
    restart: always
    build: .
    container_name: startup_gift
    #    links:
    #      - postgres:postgres
    #      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_service

    environment:
      DEBUG: 'true'
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

#  nginx:
#    restart: always
#    build: ./nginx/
#    ports:
#      - "80:80"
#    volumes:
#      - web-static:/www/static
#    links:
#      - web:web



#  redis:
#    restart: always
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    volumes:
#      - redisdata:/data

volumes:
  web-django:
  web-static:
  pgdata:
#  redisdata:
